tox.ini

This PR add Python 3.9 to the test environment and remove the Python 3.6 version. Python 3.6 will only be support until Dec, 2021 (see e.g. https://azure.microsoft.com/en-us/updates/community-support-for-python-36-is-ending-on-23-december-2021/), so it's maybe better to not support it anymore.

Add Python 3.9 to test environments

---

pylira/__init__.py
pylira/src/lira.cpp
pylira/tests/test_core.py

This PR adds an example for binding a struct. It is mostly taken from the pybin11 documentation here: https://pybind11.readthedocs.io/en/latest/classes.html#creating-bindings-for-a-custom-type It also adds a test to verify it works correctly.

Add pybind 11 struct example and tests

---

pylira/src/lira.cpp
pylira/tests/test_core.py

This PR adds a minimal example using pybind's `py::vectorize` to vectorise the `add` function and make it work with Numpy arrays. This not the way we want the wrapper to work in the end, but this examples still makes sure that the build system and test works correctly with Numpy

Add minimal numpy example using pybind vectorize

---

pylira/__init__.py
pylira/src/lira.cpp
pylira/tests/test_core.py

This PR adds a second Numpy wrapper example, that make use of the buffer protocol for the wrapping. This is mostly taken from pybind11 documentation. It could be interesting to adapt this later to the [direct access method](https://pybind11.readthedocs.io/en/stable/advanced/pycpp/numpy.html#direct-access).

Add minimal numpy wrapper example #2

---

MANIFEST.in
pylira/src/lira.h
pylira/src/lirabind.cpp
setup.py

This PR splits the pybind11 bindings from the source code and adapts the build system accordingly.

Split Python bindings from source code

---

.clang-format
docs/pylira/developer.rst
pylira/src/lira.h
pylira/src/lirabind.cpp

This PR adds a `.clang-format` file and runs `clang-format` on the `src` folder. I don't really care about the actual style used as long as it is uniform. The `.clang-format` can be modified anytime later...

Use clang format to format C code

---

pylira/core.py
pylira/data/core.py
pylira/src/lira.h
pylira/src/lirabind.cpp
pylira/tests/test_core.py

This PR fixes the seg fault causing parts of LIRA's C code. The main culprits for the seg faults appear to be the R functions ```S_alloc``` and ```Rprintf```. ```S_alloc``` is swapped with ```calloc``` and all the ```printf```-like functions are renamed to ```prinf_d```, which is a wrapper around ```printf```, and only prints if ```DEBUG``` is defined. In addition, the ```Get/PutRNGState``` functions are replaced with the ```set_seed``` function.
This PR also fixes a few variables to make them consistent with LIRA's expectations.

Removes seg fault-causing R functions from LIRA C code

---

pylira/tests/test_core.py

This PR adds asserts on the parameter trace of the current tests. However I noticed that currently the random number generation in R is not seeded. The results are not deterministic. For meaningful and reproducible testing we need to change this. @infinitron Any concrete suggestion how to achieve this? Probably we just introduce and additional seed integer that is passed down to the `image_analysis_R` method?

Add parameter trace asserts

---

pylira/core.py
pylira/src/lirabind.cpp
pylira/tests/test_core.py

This PR adds the `fit_bkgscl` parameters to the `image_analysis` binding methods and exposes it to the `LIRADeconvolver` class.

Expose fit background scale parameter

---

pylira/core.py
pylira/tests/test_core.py
pylira/utils/plot.py

This PR adds the trace table to the result of the `LIRADeconvolver` class, this is very convenient for interactive usage. I also added the configuration meta date to the table.

Add trace table to Deconvolver result

---

pylira/core.py
pylira/tests/test_core.py

This PR implements a `LIRADeconvolverResult` which provide convenience access to the results, such as posterior mean, parameter and image trace. In future PRs I'll add serialisation, plotting and combination of result objects.

Implement LIRADeconvolverResult object

---

pylira/core.py
pylira/tests/test_core.py
pylira/utils/io.py

This PR adds `LIRADeconvolverResult.write` methods to be able to serialize the result including posterior mean, parameter trace and image trace.

Implement result FITS serialization

---

pylira/__init__.py
pylira/core.py
pylira/tests/test_core.py
pylira/utils/io.py

This PR adds a `LIRADeconvolverResult.read` method to be able to read a result back from FITS.

Implement result FITS serialization read

---

pylira/core.py
pylira/utils/plot.py
pylira/utils/tests/test_plot.py

This PR implement a `plot_pixel_trace` helper method and exposes it as `LIRADeconvolverResult.plot_pixel_trace()`. I generates a plot like this:
Which is very useful to check the convergence of the algorithm for a specific pixel.

Implement pixel trace plotting

---

pylira/core.py
pylira/utils/plot.py
pylira/utils/tests/test_plot.py

This pull request is a follow up to #35. It includes the plotting of the traces of the neighboring pixels to be able to see any correlations. The resulting plot looks like:

Pixel trace plotting follow up

---

pylira/core.py
pylira/tests/test_core.py
pylira/utils/plot.py

This PR add a `__str__` method to print the current state of the `LIRADeconvolver` object.

Add LIRADeconvolver.__str__

---

pylira/src/lira.h

This PR removes the dependency on `R.h` and replaces the error handling by standard library error handling.

Remove R.h dependency

---

.github/workflows/ci_tests.yml
.gitignore
pylira/core.py
pylira/src/lira.h
pylira/src/lirabind.cpp
pylira/tests/test_core.py

This pull request adds a `random_seed` parameter to the `bayes_image_analysis` and `image_analysis_R` methods to allow for deterministic testing. I also introduced a `LIRADeconvolver.random_state` attribute which allow to handle the random seeds using `np.random.RandomState`. I adapted the tests to exact testing now, let's see if the CI passed and results are independent of the used platform.

Add random seed parameter

---

docs/conf.py
docs/index.rst
docs/pylira/api.rst
docs/pylira/changelog.rst
docs/pylira/developer.rst
docs/pylira/index.rst
docs/pylira/references.rst
docs/pylira/user.rst
setup.cfg

This PR changes the documentation to https://pydata-sphinx-theme.readthedocs.io/en/latest/, which is the theme used by many bigger projects such as Numpy and matplotlib.

Change to pydata sphinx theme

---

.gitignore
docs/conf.py
docs/pylira/user/index.rst
docs/pylira/user/tutorials/index.rst
docs/pylira/user/tutorials/notebooks/point_source.md
setup.cfg

This PR adds the setup for including tutorial notebooks in the documentation as well as a first example running pylira on a simple point source example.

Add docs tutorials notebooks setup and first example

---

docs/conf.py
docs/pylira/user/tutorials/notebooks/point_source.md

This PR adds a download link to the end of the tutorial for downloading the `.ipynb` file.

Add download link to tutorials

---

docs/pylira/user/tutorials/index.rst
docs/pylira/user/tutorials/notebooks/mcmc-deconvolution-intro.md

This PR adds a tutorial explaining the basics of MCMC based deconvolution. It includes a minimal simplified pure Numpy implementation of MCMC deconvolution that I implemented as part of the learning process to understand how LIRA works. I thought it might be useful for others as well, so I'm adding it to the docs.

Add MCMC deconvolution basics tutorial

---

docs/pylira/user/tutorials/notebooks/mcmc-deconvolution-intro.md
pylira/utils/convolution.py

This PR implements a minimal version of `scipy.signal.fftconvolve` to avoid the scipy dependency for now. The currently used `astropy.convolution.convolve_fft` introduces a bit to much overhead, as the method is call in the likelihood evaluation loop.

Implement minimal fftconvolve 

---

pylira/core.py
setup.cfg

This PR adds a method `.plot_image_tarce_interactive()`, which is very helpful to scroll through the image trace interactively in a Jupiter notebook.

Add method to plot image trace interactively

---

pylira/core.py
pylira/data/core.py
pylira/data/tests/test_core.py
pylira/tests/test_core.py

This PR adds a `random_state` to the data simulation methods, to avoid the re-seed, which does not allow to simulated multiple datasets of the same type.

Add random state to data simulation methods
